name: PR emoji stripper
on:
  pull_request_target:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  title_and_changelog:
    runs-on: ubuntu-20.04
    steps:
    - uses: ./tools/ci/pr-emoji-stripper
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        title: true
        body: true
        body-after: ":cl:"
        body-before: "/:cl:"
